version: '3.6'

services:
  web:
    build: .
    # command: python3 manage.py runserver 0.0.0.0:8000
    command: gunicorn oneStop.wsgi:application --bind 0.0.0.0:8000

    volumes:
      - .:/usr/src/
    expose:
      - 8000
    env_file: .env.docker
    depends_on:
      - db-postgres
      - db-mongo
  db-postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file: .env-postgres
    ports:
      - "5432:5432"
  db-mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo_data:/data/db
    env_file: .env-mongodb
    ports:
      - "27017:27017"
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - web

volumes:
  postgres_data:
  mongo_data: