name: Django CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    services:
        postgres:
          image: postgres:12.3
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: db
          ports:
            - 5432:5432
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: MongoDB in GitHub Actions
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 4.2

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: .env.example to .env
      run : cp .env.example .env
    - name: Run migrate
      run: python manage.py migrate
    - name: Check
      run: |
        - python manage.py check
